# Welcome to the Spheron Network! 🚀☁
# This file is called a Infrastructure Composition Language (ICL)
# ICL is a human friendly data standard for declaring deployment attributes.
# The ICL file is a "form" to request resources from the Network.
# ICL is compatible with the YAML standard and similar to Docker Compose files.

---
version: "1.0"
services:
  gpu-test:
    image: anandhavihari/spheron-ai-celebrity-chatbot:latest
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - TEST=test
profiles:
  name: hello-world
  mode: provider
  duration: 1h
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      attributes:
        region: us-central
      pricing:
        gpu-test:
          token: USDT
          amount: 5
deployment:
  gpu-test:
    westcoast:
      profile: gpu-test
      count: 1
